/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crypto;

import javafx.application.Application;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ToolBar;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;


public class App extends Application {

    public static void main(String[] args) {
        launch();
    }

    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        BorderPane borderPane = new BorderPane(l);
        Scene scene = new Scene(borderPane, 640, 480);
        ToolBar toolbar = new ToolBar();
        HBox statusbar = new HBox();
        VBox appContent = new VBox();
        borderPane.setTop(toolbar);
        borderPane.setCenter(appContent);
        borderPane.setBottom(statusbar);

        HBox unencryptedPane = new HBox();
        unencryptedPane.getChildren().add(new Label("unencryptedPane"));
        unencryptedPane.setBorder(new Border(new BorderStroke(Color.BLACK, BorderStrokeStyle.SOLID, CornerRadii.EMPTY, BorderWidths.DEFAULT)));

        HBox encryptedPane = new HBox();
        encryptedPane.getChildren().add(new Label("encryptedPane"));
        encryptedPane.setBorder(new Border(new BorderStroke(Color.BLACK, BorderStrokeStyle.SOLID, CornerRadii.EMPTY, BorderWidths.DEFAULT)));


        HBox cypherPane = new HBox();
        cypherPane.getChildren().add(new Label("cypherPane"));
        cypherPane.setBorder(new Border(new BorderStroke(Color.BLACK, BorderStrokeStyle.SOLID, CornerRadii.EMPTY, BorderWidths.DEFAULT)));


        appContent.getChildren().add(unencryptedPane);
        appContent.getChildren().add(cypherPane);
        appContent.getChildren().add(encryptedPane);
        stage.setScene(scene);
        stage.show();
    }

}